### PR TITLE
Add Dockerfile and compose and fix code style and deps

### PR DESCRIPTION
**Pull request by seyfer**
Have added

* docker and compose
* fix deps
* fix code style

just for fun :)

### CODE REVIEW

**Comment by john-pickett** [comment]
Thanks for the contribution, but I don't think most of these changes are necessary. The missing Vuetify dependency has been fixed.

**Comment by seyfer** [comment]
@john-pickett It is wrong. Code style is very important. Also, I have added better checks with use of Number,
you are comparing string with number sometimes without strict check. That's wrong.

But as you wish, as you like...

**Comment by seyfer** [comment]
@john-pickett also I have added Docker config. It is great to run the app in docker, very easy.

**Comment by john-pickett** [comment]
If you'd like to submit a new pull request with just the Docker config, I could take a look at that.

**Comment by seyfer** [comment]
@john-pickett ok, will do

**Pull request closed without merging**
